from snakemake.utils import min_version
import pandas as pd
import fnmatch

# Initialization ----

# Set min. snakemake version for compatability.
min_version("7.31.1")


# Specify configuration file.
configfile: "config/config.yaml"

# Read sample metadata. ----
samplesheet = pd.read_csv(config["path_samples"], sep="\t", dtype=str, comment="#")

# Set working directory to output directory.
workdir: config["dir_output"]


wildcard_constraints:
    species="|".join([re.escape(x) for x in samplesheet["species"]]),
    tissue="|".join([re.escape(x) for x in samplesheet["tissue"]]),
    replicate="|".join([re.escape(x) for x in samplesheet["replicate"]]),
    sample="|".join([re.escape(x) for x in samplesheet["sample"]]),


# Workflow output. ----


rule all:
    input:
        lambda w: [
            "chicago/design/{species}/{sample}.chicinput".format(
                sample=sample, species=species, tissue=tissue, replicate=replicate
            )
            for sample, species, tissue, replicate in zip(
                samplesheet["sample"],
                samplesheet["species"],
                samplesheet["tissue"],
                samplesheet["replicate"],
            )
        ],


# Load rules ----

include: "rules/step1_prepare_genomes.smk"
include: "rules/step2_alignment.smk"
include: "rules/step3_chicago.smk"
